# ICD10 suggestions and selections
#
# These functions make suggestions for equivalent ICD10 codes
# The suggestions can be selected manually as appropriate with the select functions
# The output from the select function is a vector of selected codes
#
#
# @param codes List of non-ICD10 codes to map \code{list(icd9 = c("123", "456"), read_v3 = c("123", "456"))}
# @param icd10_suggestions Data frame generated by \code{suggest_icd10_codes(codes)}

suggest_icd10_codes = function(codes){

  data(read_v3_icd10)
  data(read_v2_icd10)
  data(icd9_to_icd10)
  data(icd10_lookup)

  if(!is.null(codes$read_v3)){
    icd10_read_v3 = read_v3_icd10 %>%
      filter(read_code %in% codes$read_v3) %>%
      pull(icd10_code)
  } else {
    icd10_read_v3 = c(NULL)
  }

  if(!is.null(codes$read_v2)){
    icd10_read_v2 = read_v2_icd10 %>%
      filter(read_code %in% codes$read_v2) %>%
      pull(icd10_code)
  } else {
    icd10_read_v2 = c(NULL)
  }

  if(!is.null(codes$icd9)){
    icd10_icd9 = icd9_to_icd10 %>%
      filter(icd9_code %in% codes$icd9) %>%
      pull(icd10_code)
  } else {
    icd10_icd9 = c(NULL)
  }

  icd10_codes = c(icd10_read_v3,
                  icd10_read_v2,
                  icd10_icd9) %>%
    compact() %>%
    unique()

  if (length(icd10_codes) > 0){


    cat("The generated table contains suggestions for ICD10 codes based on the ICD9, read_v3 and read_v2 codes provided.\nMany of these codes will be too general and therefore not apply.\nOPCS codes are not mapped to ICD10 so please consider searching these separately for procedures performed only for the condition.\n")

    suggestions = icd10_lookup %>%
      filter(str_detect(icd10, paste0("^", icd10_codes, collapse = "|")))

  } else {

    cat("There were no matching ICD10 codes identified.\n")
    suggestions = c(NULL)

  }
}

select_icd10_codes = function(icd10_suggestions, selection){
  if (!(is.numeric(selection)) %>% reduce(.f = `|`)) {
    print("Selection must be a vector of all positive or all negative row integers.")
  } else{
    if (any(selection == 0)) {
      print("Selection must be a vector of all positive or all negative row integers and not 0.")
    } else{
      if (any(selection > 0) & any(selection < 0)) {
        print("Selection must be a vector of all positive or all negative row integers and not a combination.")
      } else {
        if (identical(sort(names(icd10_suggestions)), sort(c("icd10_code ", "term_description")))){
          print("icd10_suggestions should be a data frame generated by suggest_icd10_codes()")
        } else {
          icd10_suggestions %>%
            slice(selection) %>%
            pull(icd10_code) %>%
            unique() %>%
            dput()
        }
      }
    }
  }
}
