# ICD9 suggestions and selections
#
# These functions make suggestions for equivalent ICD9 codes
# The suggestions can be selected manually as appropriate with the select functions
# The output from the select function is a vector of selected codes
#
#
# @param codes List of non-ICD9 codes to map \code{list(icd10 = c("A01", "A02"), read_v3 = c("123", "456"))}
# @param icd9_suggestions Data frame generated by \code{suggest_icd9_codes(codes)}


suggest_icd9_codes = function(codes){

  data(read_v3_icd9)
  data(read_v2_icd9)
  data(icd9_to_icd10)
  data(icd9_lookup)

  if(!is.null(codes$read_v3)){
    icd9_read_v3 = read_v3_icd9 %>%
      filter(read_code %in% codes$read_v3) %>%
      pull(icd9_code)
  } else {
    icd9_read_v3 = c(NULL)
  }

  if(!is.null(codes$read_v2)){
    icd9_read_v2 = read_v2_icd9 %>%
      filter(read_code %in% codes$read_v2) %>%
      pull(icd9_code)
  } else {
    icd9_read_v2 = c(NULL)
  }

  if(!is.null(codes$icd10)){
    icd9_icd10 = icd9_to_icd10 %>%
      filter(icd10_code %in% codes$icd10) %>%
      pull(icd9_code)
  } else {
    icd9_icd10 = c(NULL)
  }

  icd9_codes = c(icd9_read_v3,
                 icd9_read_v2,
                 icd9_icd10) %>%
    compact() %>%
    unique()

  if (length(icd9_codes) > 0){


    cat("The generated table contains suggestions for ICD9 codes based on the ICD10, read_v3 and read_v2 codes provided.\nMany of these codes will be too general and therefore not apply.\nOPCS codes are not mapped to ICD9 so please consider searching these separately for procedures performed only for the condition.\n")

    suggestions = icd9_lookup %>%
      filter(str_detect(icd9, paste0("^", icd9_codes, collapse = "|")))

  } else {

    cat("There were no matching ICD9 codes identified.\n")
    suggestions = c(NULL)

  }
}

select_icd9_codes = function(icd9_suggestions, selection){
  if (!(is.numeric(selection)) %>% reduce(.f = `|`)) {
    print("Selection must be a vector of all positive or all negative row integers.")
  } else{
    if (any(selection == 0)) {
      print("Selection must be a vector of all positive or all negative row integers and not 0.")
    } else{
      if (any(selection > 0) & any(selection < 0)) {
        print("Selection must be a vector of all positive or all negative row integers and not a combination.")
      } else {
        if (identical(sort(names(icd9_suggestions)), sort(c("icd9_code ", "term_description")))){
          print("icd9_suggestions should be a data frame generated by suggest_icd9_codes()")
        } else {
          icd9_suggestions %>%
            slice(selection) %>%
            pull(icd9_code) %>%
            unique() %>%
            dput()
        }
      }
    }
  }
}
