# Read V3 suggestions and selections
#
# These functions make suggestions for equivalent READ codes
# The suggestions can be selected manually as appropriate with the select functions
# The output from the select function is a vector of selected codes
#
#
# @param codes List of non-READ V3 codes to map \code{list(icd10 = c("A01", "A02"), icd9 = c("123", "456"))}
# @param read_v3_suggestions Data frame generated by \code{suggest_read_v3_codes(codes)}

suggest_read_v3_codes = function(codes){

  data(read_v3_icd9)
  data(read_v3_icd10)
  data(read_v3_opcs4)
  data(read_v3_lookup)

  if(!is.null(codes$icd9)){
    read_v3_icd9 = read_v3_icd9 %>%
      filter(icd9_code %in% codes$icd9) %>%
      pull(read_code)
  } else {
    read_v3_icd9 = c(NULL)
  }


  if(!is.null(codes$icd10)){
    read_v3_icd10 = read_v3_icd10 %>%
      filter(icd10_code %in% codes$icd10) %>%
      pull(read_code)
  } else {
    read_v3_icd10 = c(NULL)
  }

  if(!is.null(codes$opcs4)){
    read_v3_opcs4 = read_v3_opcs4 %>%
      filter(opcs4_code %in% codes$opcs4) %>%
      pull(read_code)
  } else {
    read_v3_opcs4 = c(NULL)
  }


  read_v3 = c(read_v3_icd9,
              read_v3_icd10,
              read_v3_opcs4) %>%
    compact() %>%
    unique() %>%
    str_remove_all("\\.+$")

  if (length(read_v3) > 0){


    cat("The generated table contains suggestions for Read Code (Version 3) codes that are equivalent to the ICD9, ICD10 and OPCS4 codes provided.\nMany of these codes will be too general and therefore not apply.\nSpecial care is needed to ensure that the read code is specific to your condition as some read codes cover hundreds of loosely related conditions.\nIt is also recommended to search manually for your disease string in the View() pane as some codes are not mapped.\n")

    suggestions = read_v3_lookup %>%
      filter(str_detect(read_code, paste0("^", read_v3, collapse = "|")))

    suggestions_crossref = suggestions %>%
      filter(str_detect(term_description, "^See ")) %>%
      mutate(crossref = word(term_description, -1)) %>%
      select(-term_description) %>%
      left_join(read_v3_lookup %>% rename(crossref = read_code), by = "crossref") %>%
      select(-crossref)

    suggestions %>%
      filter(!str_detect(term_description, "^See ")) %>%
      bind_rows(suggestions_crossref)
  } else {

    cat("There were no matching READ codes identified.\n")
    suggestions = c(NULL)

  }
}


select_read_v3_codes = function(read_v3_suggestions, selection){
  if (!(is.numeric(selection)) %>% reduce(.f = `|`)) {
    print("Selection must be a vector of all positive or all negative row integers.")
  } else{
    if (any(selection == 0)) {
      print("Selection must be a vector of all positive or all negative row integers and not 0.")
    } else{
      if (any(selection > 0) & any(selection < 0)) {
        print("Selection must be a vector of all positive or all negative row integers and not a combination.")
      } else {
        if (identical(sort(names(read_v3_suggestions)), sort(c("read_code ", "term_description")))){
          print("read_v3_suggestions should be a data frame generated by suggest_read_v3_codes()")
        } else {
          read_v3_suggestions %>%
            slice(selection) %>%
            pull(read_code) %>%
            unique() %>%
            dput()
        }
      }
    }
  }
}
