# Read V2 suggestions and selections
#
# These functions make suggestions for equivalent READ codes
# The suggestions can be selected manually as appropriate with the select functions
# The output from the select function is a vector of selected codes
#
# \code{suggest_combination_read_v2_codes} suggests codes which were mapped to combinations
# These are cases where ICD code x and ICD code y are required together for READ code
#
#
# @param codes List of non-READ V2 codes to map \code{list(icd10 = c("A01", "A02"), icd9 = c("123", "456"))}
# @param read_v2_suggestions Data frame generated by \code{suggest_read_v2_codes(codes)}


suggest_read_v2_codes = function(codes){

  data(read_v2_icd9)
  data(read_v2_icd10)
  data(read_v2_opcs4)
  data(read_v2_lookup)

  if(!is.null(codes$icd9)){
    read_v2_icd9 = read_v2_icd9 %>%
      filter(icd9_code %in% codes$icd9) %>%
      pull(read_code)
  } else {
    read_v2_ic9 = c(NULL)
  }

  if(!is.null(codes$icd10)){
    read_v2_icd10 = read_v2_icd10 %>%
      filter(icd10_code %in% codes$icd10) %>%
      pull(read_code)
  } else {
    read_v2_icd10 = c(NULL)
  }

  if(!is.null(codes$opcs4)){
    read_v2_opcs4 = read_v2_opcs4 %>%
      filter(opcs4_code %in% codes$opcs4) %>%
      pull(read_code)
  } else {
    read_v2_opcs4 = c(NULL)
  }

  read_v2 = c(read_v2_icd9,
              read_v2_icd10,
              read_v2_opcs4) %>%
    unique() %>%
    str_remove_all("\\.+$")

  if (length(read_v2) > 0){


    cat("The generated table contains suggestions for Read Code (Version 2) codes that are equivalent to the ICD9, ICD10 and OPCS4 codes provided.\nMany of these codes will be too general and therefore not apply.\nRead Codes applicable to cases in which two or more ICD or OPCS codes must be combined, are not included.\nTo see these codes with more than one ICD/OPCS code required, use 'suggest_combination_read_v2_codes()\nSpecial care is needed to ensure that the read code is specific to your condition as some read codes cover hundreds of loosely related conditions.\nIt is also recommended to search manually for your disease string in the View() pane as some codes are not mapped.\n")

    suggestions = read_v2_lookup %>%
      filter(str_detect(read_code, paste0("^", read_v2, collapse = "|")))

    suggestions_crossref = suggestions %>%
      filter(str_detect(term_description, "^See ")) %>%
      mutate(crossref = word(term_description, -1)) %>%
      select(-term_description) %>%
      left_join(read_v2_lookup %>% rename(crossref = read_code), by = "crossref") %>%
      select(-crossref)

    suggestions %>%
      filter(!str_detect(term_description, "^See ")) %>%
      bind_rows(suggestions_crossref)
  } else {

    cat("There were no matching READ codes identified.\n")
    suggestions = c(NULL)

  }
}


suggest_combination_read_v2_codes = function(codes, read_v2_icd9_complex, read_v2_icd10_complex, read_v2_opcs4_complex, read_v2_lookup) {

  data(read_v2_icd9_complex)
  data(read_v2_icd10_complex)
  data(read_v2_opcs4_complex)
  data(read_v2_lookup_complex)

  if(!is.null(codes$icd9)){
    read_v2_icd9_complex = read_v2_icd9_complex %>%
      filter(first %in% codes$icd9 | second %in% codes$icd9) %>%
      pull(read_code)
  } else {
    read_v2_icd9_complex = c(NULL)
  }

  if(!is.null(codes$icd10)){
    read_v2_icd10_complex = read_v2_icd10_complex %>%
      filter(first %in% codes$icd10 | second %in% codes$icd10) %>%
      pull(read_code)
  } else {
    read_v2_icd10_complex = c(NULL)
  }

  if(!is.null(codes$opcs4)){
    read_v2_opcs4_complex = read_v2_opcs4_complex %>%
      filter(first %in% codes$opcs4 | second %in% codes$opcs4) %>%
      pull(read_code)
  } else {
    read_v2_opcs4_complex = c(NULL)
  }


  read_v2_complex = c(read_v2_icd9_complex,
                      read_v2_icd10_complex,
                      read_v2_opcs4_complex) %>%
    unique() %>%
    str_remove_all("\\.+$")


  if (length(read_v2) > 0){


    cat("The generated table contains suggestions for Read Code (Version 2) codes that are equivalent to the combined ICD9, ICD10 and OPCS4 codes provided.\nEach READ code was thought to be applicable only if two separate ICD/OPCS codes were applied simultanesouly.\nIf one of these codes is thought to be relevant it can be added into the list generated from regular codes manually.\nIt is also recommended to search manually for your disease string in the View() pane as some codes are not mapped.\n")

    suggestions = read_v2_lookup %>%
      filter(str_detect(read_code, paste0("^", read_v2_complex, collapse = "|")))

    suggestions_crossref = suggestions %>%
      filter(str_detect(term_description, "^See ")) %>%
      mutate(crossref = word(term_description, -1)) %>%
      select(-term_description) %>%
      left_join(read_v2_lookup %>% rename(crossref = read_code), by = "crossref") %>%
      select(-crossref)

    suggestions %>%
      filter(!str_detect(term_description, "^See ")) %>%
      bind_rows(suggestions_crossref)
  } else {

    cat("There were no matching READ codes identified.\n")
    suggestions = c(NULL)

  }
}

select_read_v2_codes = function(read_v2_suggestions, selection){
  if (!(is.numeric(selection)) %>% reduce(.f = `|`)) {
    print("Selection must be a vector of all positive or all negative row integers.")
  } else{
    if (any(selection == 0)) {
      print("Selection must be a vector of all positive or all negative row integers and not 0.")
    } else{
      if (any(selection > 0) & any(selection < 0)) {
        print("Selection must be a vector of all positive or all negative row integers and not a combination.")
      } else {
        if (identical(sort(names(read_v2_suggestions)), sort(c("read_code ", "term_description")))){
          print("read_v2_suggestions should be a data frame generated by suggest_read_v2_codes()")
        } else {
          read_v2_suggestions %>%
            slice(selection) %>%
            pull(read_code) %>%
            unique() %>%
            dput()
        }
      }
    }
  }
}
